### ISSUE TITLE
On Android Working as a toast only !

### ISSUE THREAD

**Issue by harsukhbir** [CaffeinaLab/Ti.Notifications#13]
HI,

Hope you are doing great!!

I have tried this widget and found on android its not working as expected. Its  working as a toast only.

Please provide me the steps to make it work for android. Any help will be appreciated.

Regards,

**Comment by kopiro** [comment]
Are you passing a `view` ?

**Comment by adamkearsley** [comment]
@harsukhbir 

As android works with Views you need to pass a view variable;
Example:
```
Alloy.Globals.notify.show({message: 'MyMessage', duration: 2500, view:$.myMainView});
```

**Comment by harsukhbir** [comment]
Thanks for your responses !

Yes Its working in the view but not When I am using the Tab group view its not working for me. Do you have any idea to use in the TabBar group?

**Comment by kopiro** [comment]
What's wrong with `TabBar` ?

**Comment by harsukhbir** [comment]
$ not defined.

**Comment by kopiro** [comment]
Are you sure that is not a bug in your code?
Could you paste a snippet?

**Comment by harsukhbir** [comment]
Now I am trying with tabGroup id. If not work then I will share

**Comment by harsukhbir** [comment]
knockApp.notifier.show
		({
		    message: 'Recived new message form '+data.userId+' : '+data.text,
		  	view: $.tabs,  //view: $.mainScreen also not worked
		    icon: 'appicon.png',
		    pushForce: 10,
		    duration: 2500,
		    elasticity: 0.5, // iOS7+ only
		    pushForce: 30, // iOS7+ only
		    usePhysicsEngine: true, // disable if you don't want on iOS7+
		    animationDuration: 200,
		});

**Comment by kopiro** [comment]
In which context are you calling this code?
In the Alloy controller?

Are you sure that `$` is available, try to debug it.

**Comment by adamkearsley** [comment]
How are you creating the tabView?
```
var tabView = Ti.UI.createTabGroup(...);
knockApp.notifier.show
({
message: 'Recived new message form '+data.userId+' : '+data.text,
view: tabView, //view
icon: 'appicon.png',
pushForce: 10,
duration: 2500,
elasticity: 0.5, // iOS7+ only
pushForce: 30, // iOS7+ only
usePhysicsEngine: true, // disable if you don't want on iOS7+
animationDuration: 200,
});
```
OR in Alloy?

xml
```
<TabGroup id="myTabGroup">
...
</TabGroup>
```
js
```
knockApp.notifier.show
({
message: 'Recived new message form '+data.userId+' : '+data.text,
view: $.myTabGroup, //view
icon: 'appicon.png',
pushForce: 10,
duration: 2500,
elasticity: 0.5, // iOS7+ only
pushForce: 30, // iOS7+ only
usePhysicsEngine: true, // disable if you don't want on iOS7+
animationDuration: 200,
});
```

**Comment by harsukhbir** [comment]
I have created my tabView in the Alloy. The problem is I am using js files for some reasons in the lib folder. 

I declared ORTC handler in the Alloy for global use and I am trying to access tab group in this js file. 
ortcHandler: require('ortcHandler'),

**Comment by kopiro** [comment]
You have to pass the controller to access to `$`

**Comment by harsukhbir** [comment]
Thanks for your kind help. 

I am very new in Titanium. Could you paste a snippet for how to pass controller in js.

Thanks in Advance

**Comment by kopiro** [comment]
In the controller file, you have to reference the `$` variable to the function that uses it.

controller.js
```js
var lib = require('external');
lib.myFunction({ controller: $ });
```


external.js
```js
exports.myFunction = function(obj) {
   Notifier.show({ view: obj.controller.getView() });
};
```

**Comment by adamkearsley** [comment]
Not sur if this helps... but i use my notifications in this way

alloy.js
```
Alloy.Globals.notify = Alloy.createWidget('com.caffeinalab.titanium.notifications');
```

index.js
```
Ti.App.addEventListener('showAlert', function(e){
	OS_IOS ? Alloy.Globals.notify.show({message: e.message, duration: e.duration}):Alloy.Globals.notify.show({message: e.message, duration: e.duration, view:e.view});
});
```

anyController.js
```
Ti.App.fireEvent('showAlert', {message:'Loading...', duration: 2500, view:$.myView});
```

This works for iOS and Android.

**Comment by adamkearsley** [comment]
Also i pass my views in this method

controller.js
```
var someCommonJS = require('someCommonJS');
someCommonJS.myFunction('SomeString', $myView);
```

someCommonJS.js
```
exports.myFunction = function(myString, myView)
{
      Ti.App.fireEvent('showAlert', {message: myString, duration: 2500, view:myView});
};
```

Hope it helps :)

**Comment by kopiro** [comment]
So, does it works?

**Comment by harsukhbir** [comment]
Hi Thanks for your valuable time. Yes Its worked for me. Sorry I was stuck in some personal issues so unable to update the git.

Thanks guys for your help and time
