### ISSUE TITLE
Can we have example for Ti Classic 

### ISSUE THREAD

**Issue by srikpunu** [CaffeinaLab/Ti.Notifications#14]
This is not an issue. This is request. 

Please provide Ti Classic example.

**Comment by kopiro** [comment]
Ti.Classic doesn't have widgets.

**Comment by srikpunu** [comment]
Thank you Sir. Do you know any notification module similar to your widget for classic. Sorry to ask here. Please suggest if you know.

**Comment by kopiro** [comment]
No, I don't know...
The question is, why do you use Ti.Classic instead of Alloy?
