### ISSUE TITLE
Multiple push notifications 

### ISSUE THREAD

**Issue by darkhorse2013** [CaffeinaLab/Ti.Notifications#17]
I want to use this as part of push notifications, if the push notifications are stacked, the banner only shows the last push notification one. How can I use the module to handle this better?

**Comment by kopiro** [comment]
Are you using the same instance of the loader, or allocating a new instance?

Single instance:
```js
var Loader = Alloy.createWidget();
Loader.show();

// ...

Loader.show()
```

Multiple instance:
```js
Alloy.createWidget().show();
// ...
Alloy.createWidget().show();
```

**Comment by darkhorse2013** [comment]
So if the user gets 20 push notifications, I need the banner to show 20 times.

Will doing it this way cause performance issues? Multiple objects being created at once?

**Comment by darkhorse2013** [comment]
Hi,

I have tried this:


Alloy.createWidget('com.caffeinalab.titanium.notifications').show({
	message : 'Notification Test',
	icon : '/appicon.png',
	pushForce : 10,
	//style : 'info', // sets the message background to blue (50% opacity)
	duration : 2500,
	onClick : function() {
		alert("OH, you clicked me!\nDo you think I'm weird?");
	}
});

Alloy.createWidget('com.caffeinalab.titanium.notifications').show({
	message : 'Notification Test 2',
	icon : '/appicon.png',
	pushForce : 10,
	//style : 'info', // sets the message background to blue (50% opacity)
	duration : 2500,
	onClick : function() {
		alert("OH, you clicked me!\nDo you think I'm weird?");
	}
	// Show the widget, and override defaults
});

It only shows the last widget I have created, as opposed to sequentially.

**Comment by kopiro** [comment]
Maybe because the're running in the same thread.
`setInterval` do the trick.

http://drop.caffeina.co/001k3B3l0o2j
